### ISSUE TITLE
How is pyQuil being benchmarked?

### ISSUE THREAD

**Issue by stylewarning** [qulacs/qulacs#113]
PyQuil offers two simulators:

1. The Python-based pyQVM, built into pyQuil
2. The Forest SDK QVM, which is a native binary.

The latter (i.e., the `qvm` application) offers two simulation modes, standard interpreted mode, and compiled mode. The latter can be enabled with the `-c` command line option to the QVM, i.e.,

```
$ qvm -S -c
```

I would be curious to see benchmarks for these things.

**Comment by stylewarning** [comment]
As a note I've begun to add this to the QVM as a benchmark option. With [this PR](https://github.com/rigetti/qvm/pull/43), one can do:
```
qvm --verbose --benchmark --benchmark-type qualcs -c
```
This will run the benchmark as specified in the README (10 layers of random `RX`, 9 interleaved layers of random `CNOT`.)

**Comment by corryvrequan** [comment]
Thank you for being interested in qulacs, @stylewarning,

The benchmark of qulacs on the top page is done with 1) python-bsed simulator.
I believe simulation by Forest SDK is faster than that by python-based one.
Though I'm also interested in faster one, we used slower one due to two reasons:
1) Forest SDK was not released when this benchmarking is done.
2) Currently used benchmarking computer is Windows, and Forest SDK does not support windows.

We plan to update benchmarking codes and environment in this month, and plan to make all benchmarking code public. In this update, we also plan to add Forest SDK to the list.

**Comment by stylewarning** [comment]
Sure, happy to receive PRs. Also happy if you just file an issue on the qvm repo and we would be happy to look at it. Cheers.
