### ISSUE TITLE
Review Request for "quantum-benchmarks" 

### ISSUE THREAD

**Issue by Roger-luo** [qulacs/qulacs#177]
Hi qulacs folks,

I recently started [this benchmark project](https://github.com/Roger-luo/quantum-benchmarks) for our next coming paper about [Yao.jl](https://github.com/QuantumBFS/Yao.jl). 

Although I submitted a few issues here already, but since I'm not a qulacs developer, I'd like to request your review on the benchmark to make sure we write it in the right way. Please feel free to submit PRs/issues to discuss more detailed problem.

Please follow [the contribution guide](https://github.com/Roger-luo/quantum-benchmarks/blob/master/CONTRIBUTING.md) if you have questions about the benchmark utilities. We currently only have Python and Julia based benchmarks, but I believe @TysonRayJones  is working on a C/C++ benchmark, we should be able to support benchmarking C/C++ APIs soon.

Regarding to GPU benchmarks, I can't read Japanese, although I know the Chinese characters ;-) I guess there is no API that can turn GPU on at runtime at the moment? And it has to be setup by building it again with `setup_gpu.py` if I understand correctly. Thus it is not included in the benchmark (yet). But it is always nice to have more benchmark results!

Bests

**Comment by corryvrequan** [comment]
Thank you for adding our library to your benchmark project, @Roger-luo !
I will submit issue in your repository after I see benchmark codes if there is something to discuss. 
Though I only took a quick look, benchmark codes of qulacs are implemented in the right way. 

(I heard from colleagues that julia has nice runtime type-inference, but I haven't know that julia can show such a super-small overhead in small circuits!)

> I guess there is no API that can turn GPU on at runtime at the moment?

If you build qulacs with setup.py, there is no way to turn GPU on at runtime. In order to use GPU in qulacs, as you guess, you need to build qulacs again with setup_gpu.py where CUDA>=8.0 is installed. I believe you can successfully build it as far as you can build with setup.py.

Qulacs built with setup_gpu.py can treat both CPU and GPU simulation with a single library. Thus, you can use this library for both CPU and GPU benchmark. When qulacs is built with setup_gpu.py, you can import a new class "QuantumStateGpu", and you can treat this class in the same way as "QuantumState" class with few exceptions which do not matter on your benchmark. If state vector is allocated on GPU, quantum gate will automatically use update function for GPU. (i.e. there is no GPU-version gate class.) The following is an example code for applying X-gate on the 3rd qubit of 20qubits vector.

```
from qulacs import QuantumState
from qulacs.gate import X
n = 20
gate = X(3)
state = QuantumState(n)
gate.update_quantum_state(state)

from qulacs import QuantumStateGpu
state_gpu = QuantumStateGpu(n)
gate.update_quantum_state(state_gpu)
```

We are looking forward to seeing speed comparison between GPU libraries!

**Comment by Roger-luo** [comment]
Hi, thanks for the review. I read qulacs implementation briefly, since you've help me confirmed the correctness of the benchmark according to the benchmark it seems C++ didn't generate SIMDs well (we disabled multi-threading in current benchmarks, so if the algorithms are same, then SIMD matters).

As shown in `ProjectQ`'s benchmark, after handling SIMD explicitly you can get some speed up. (ProjectQ is slower in small circuit due to its arch design that cannot trace and compile the entire circuit, thus the performance is limited by Python, but I think it is not a problem for you!)

I don't think the speed up is only because Julia itself (although it does provide the possibility!), we also try to write SIMD friendly code in Julia, so the compiler can generate that for us (there is no free lunch!). You might want to try my early work on complex value SIMD in pure C: https://github.com/Roger-luo/CSIMD it provides explicit SIMD instructions on AVX, AVX2 machines. It is MIT licensed, so feel free to take it.

**Comment by corryvrequan** [comment]
Thanks for reply and sharing your SIMD codes.

I agree that main reasons of time differences might come from a support of vectorization, circuit optimization, or other efforts. Apart from that, I personally guessed runtime type-inference yields large runtime overhead and thus language like julia might have disadvantage when overhead becomes important. So it is interesting for me that this overhead is negligibly small even in small circuits.

We understood the importance of SIMD optimization, and developed experimental code tips or tried intel compilers in independent and private projects, but we haven't merge them to this repository yet since we didn't check they are compatible with all the supported environments in qulacs. We consider to try merge them later for further speed-up, and let us use your repository as a reference in that time!

**Comment by Roger-luo** [comment]
>  I personally guessed runtime type-inference yields large runtime overhead and thus language like julia might have disadvantage when overhead becomes important. So it is interesting for me that this overhead is negligibly small even in small circuits.

No, Julia is a runtime typed compiled language (it sounds strange, but that's how Julia solves the two language problem). Everything is compiled to native code, that's why we choose it in the first place. If you are interested in how this works, you can check JuliaCon videos. You can always get rid of the compilation time of static compilable code by precompiling your module.

> We consider to try merge them later for further speed-up, and let us use your repository as a reference in that time!

no problem!

**Comment by TysonRayJones** [comment]
🙌
