### ISSUE TITLE
CUDA error without loading something into GPU memory first

### ISSUE THREAD

**Issue by soudy** [qulacs/qulacs#195]
I was working on making a [Qulacs plugin](https://github.com/soudy/pennylane-qulacs/) for [PennyLane](https://github.com/XanaduAI/pennylane), and when trying to support GPU I noticed the following weird bug. When I run the following script (taken from the examples):
```python
from qulacs import Observable, QuantumCircuit, QuantumStateGpu
from qulacs.gate import Y,CNOT,merge

state = QuantumStateGpu(3)
state.set_Haar_random_state()

circuit = QuantumCircuit(3)
circuit.add_X_gate(0)
merged_gate = merge(CNOT(0,1),Y(1))
circuit.add_gate(merged_gate)
circuit.add_RX_gate(1,0.5)
circuit.update_quantum_state(state)

observable = Observable(3)
observable.add_operator(2.0, "X 2 Y 1 Z 0")
observable.add_operator(-3.0, "Z 2")
value = observable.get_expectation_value(state)
print(value)
```
It gives the following error:
```
$ python qulacs_test.py
Error: /tmp/pip-install-x493plhz/qulacs-gpu/src/gpusim/util.cuh:33, code: 35, reason: CUDA driver version is insufficient for CUDA runtime version
```

However, when I load a torch tensor into the memory of the GPU first, it _does_ work (added line 5):
```python
from qulacs import Observable, QuantumCircuit, QuantumStateGpu
from qulacs.gate import Y,CNOT,merge
import torch

torch.tensor(0, device=torch.device('cuda:0'))

state = QuantumStateGpu(3)
state.set_Haar_random_state()

circuit = QuantumCircuit(3)
circuit.add_X_gate(0)
merged_gate = merge(CNOT(0,1),Y(1))
circuit.add_gate(merged_gate)
circuit.add_RX_gate(1,0.5)
circuit.update_quantum_state(state)

observable = Observable(3)
observable.add_operator(2.0, "X 2 Y 1 Z 0")
observable.add_operator(-3.0, "Z 2")
value = observable.get_expectation_value(state)
print(value)
```
gives 
```
$ python qulacs_test.py
2.1146523414064053
```

NVIDIA info:
```
NVIDIA-SMI 418.56       Driver Version: 418.56       CUDA Version: 10.1 
```

**Comment by corryvrequan** [comment]
Thanks for report and I'm glad you are interested in using our library, @soudy!
We haven't seen that error so far, so let us give time for checking pennylane and qulacs can co-exist in our environment.

p.s.
In our experience, not the same but similar error happened about OpenMP (libgomp.so). It might be helpful for exploring what causes this error.

I guess this kind of errors happens when system files (CUDA files) used by build tool (cmake) and those found by python are different. 
Usually, all the executables search system files with the same priorities. But some big and optimized libraries control this priority (sys.path or env variables) when we import them in order to let python find the most compatible set of system files.

If this is a reason of this bug, paths of driver files or some basic shared objects of CUDA found by which command
https://docs.python.org/3.3/library/shutil.html#shutil.which
would change before and after import pytorch. If so, we need to set appropriate environment variables before launching python or building qulacs to use both libraries.
