### ISSUE TITLE
`create_observable_from_openfermion_text` fails

### ISSUE THREAD

**Issue by yoooopeeee** [qulacs/qulacs#217]
In some cases, the method `create_observable_from_openfermion_text` gives inconsistent results, when calculating expectation values.

For example, 
```py
from qulacs import QuantumState
from qulacs.observable import create_observable_from_openfermion_text
from openfermion.ops import QubitOperator

n_qubits = 2
state = QuantumState(n_qubits)

qubit_op = QubitOperator('', 1.)   # identity

observable = create_observable_from_openfermion_text(str(qubit_op))
print(observable.get_term(0).get_coef(), observable.get_term(0).get_pauli_id_list(), observable.get_term(0).get_index_list())
print(observable.get_expectation_value(state))
```

which results in, 
```
(1+0j) [] []
0.0  # should to be 1.0
```

Although the observable seems to be constructed appropriately, the expectation value is incorrect.

Another case:
```py
qubit_op = QubitOperator('Z0', 1.)

observable = create_observable_from_openfermion_text(str(qubit_op))
print(observable.get_term(0).get_coef(), observable.get_term(0).get_pauli_id_list(), observable.get_term(0).get_index_list())
print(observable.get_expectation_value(state))
```
which gives
```
(1+0j) [3] [0]
0.0  # should be 1.0
```

**Comment by corryvrequan** [comment]
I've checked this issue, and I found this code outputs "0.0" because the dimension of target Hilbert space of observable and that of quantum state are inconsistent. If dimensions are different, qulacs outputs error messages and return 0.0.

In other words, if the maximum qubit index of openfermion texts is N (meaning there are N+1 qubits), the number of qubits for quantum state must be also N+1. 
For example, the following code outputs 1.0 for both cases.

```python
from qulacs import QuantumState
from qulacs.observable import create_observable_from_openfermion_text

observable = create_observable_from_openfermion_text("(1.0+0.0j) []")
n_qubits = observable.get_qubit_count()
state = QuantumState(n_qubits)
print(observable.get_term(0).get_coef(), observable.get_term(0).get_pauli_id_list(), observable.get_term(0).get_index_list())
print(observable.get_expectation_value(state))

observable = create_observable_from_openfermion_text("(1.0+0.0j) [Z0]")
n_qubits = observable.get_qubit_count()
state = QuantumState(n_qubits)
print(observable.get_term(0).get_coef(), observable.get_term(0).get_pauli_id_list(), observable.get_term(0).get_index_list())
print(observable.get_expectation_value(state))
```

Currently, evaluation of expectation value between large quantum state and small observable is not supported. I understand this operation may be demanded.
One possible way to solve problem, i.e., defining Observable with M from openfermion text which describes up to N (<M) qubits, is adding a line 
(0.0+0.0j) [Z0 Z1 Z2 ... Z(M-1)].
to the openfermion text. This does not change expectation values and transition amplitudes, and expand Hilbert space of observable. Of course, this is an ugly solution, so I would like to implement more smart solution in the next update if possible.

**Comment by WATLE** [comment]
これ、オブザーバブルのqubitが量子bit未満でも動くように、どこかのタイミングで変更しました

**Comment by forest1040** [comment]
I changed it before so that qubit of observable works even if it is less than quantum bit.
