### ISSUE TITLE
Qulacs-Qibo benchmarks

### ISSUE THREAD

**Issue by scarrazza** [qulacs/qulacs#271]
I am contacting you because we would like to understand how the benchmark between Qulacs and Qibo on CPU has been performed in [your paper](https://arxiv.org/abs/2011.13524).

Today we rechecked both codes for the circuit in your paper (non-optimized) and we find inconsistent results with your figure 9, in fact we observe similar performance between both library. The results of this recheck and related code are reported in https://github.com/Quantum-TII/qibo/issues/289.

In order to clarify and understand the origin of such discrepancy, I appreciate if you could share the benchmark code implemented in your paper, as we did in [our paper](https://arxiv.org/abs/2009.01845) ([here](https://qibo.readthedocs.io/en/stable/benchmarks.html)).

**Comment by corryvrequan** [comment]
@scarrazza 
Thanks for contacting us on our paper. 
As referred in our paper, the benchmark code used in our paper is uploaded to the following repository.
https://github.com/qulacs/benchmark-qulacs
The benchmark codes for Qibo can be found here.
./benchmark/single(multi)thread/qibo/benchmarks.py
The above script is executed via
./benchmark/single(multi)thread/exec.sh


Note that a benchmark code performed for library comparison (Chap. VII.) is slightly different for that used in Chap.VI,
since our code is created along with the benchmark project by Yao.jl.
https://github.com/Roger-luo/quantum-benchmarks
On the other hand, this difference does not matter on the discrepancy.

While we are careful on the use of other libraries, if there is a not proper use of Qibo, 
we are very happy if you could point it out on issue or PR at the above repository,
then we would like to update codes and benchmark results on our paper.

**Comment by corryvrequan** [comment]
We performed a benchmark with the codes supllied at issue qibo#289 at our workstation, and found there is a discrepancy. Attached, please see our results and benchmark codes.
[qibo_qulacs_bench.txt](https://github.com/qulacs/qulacs/files/5619941/qibo_qulacs_bench.txt)
[qibo_qulacs_bench_py.txt](https://github.com/qulacs/qulacs/files/5620009/qibo_qulacs_bench_py.txt)

I guess this is due to the property of a benchmarking CPU, i.e, when we use CPU with large FLOPS, computing time is limited by bandwidth rather than how many complex-number operations are required. I guess a discrepancy happens when computing time is limited by FLOPS. This may be consistent since there is a discrepancy in single-thread benchmarking in your env, and the benchmark score of our CPU is worse than yours.
https://www.cpubenchmark.net/compare/Intel-Xeon-E5-2698-v4-vs-Intel-Xeon-E5-2687W-v4/2806vs2765



As for our benchmar code, we checked several changes and found two things, so let me share:
We supply
```
tf.config.threading.set_inter_op_parallelism_threads(24)
tf.config.threading.set_intra_op_parallelism_threads(24)
```
to guarantee multithreading in the benchmark of Qibo, but I found these two lines may be meaningless or may cause over parallelization. So I tried benchmark by removing these two lines, but the performance of Qibo does not change.
(24 is our total thread number. 12 threads * 2 CPU.)

While we supply 2^n - dim numpy array as the initial state in the benchmark of Qibo, I guess Qibo executes simulation with |0> state by default. I tried Qibo's benchmark without supplying the initial state, and it has improved the performance by about 20%~30%.
```
    state = np.zeros(2**nqubits, dtype=complex)
    state[0]=1
    benchmark(circuit, state) # measure time for circuit(state)
```
to
```
    benchmark(circuit) # measure time for citcuit()
```
