### ISSUE TITLE
Linker fails when compiling the Observables example

### ISSUE THREAD

**Issue by jlbosse** [qulacs/qulacs#279]
I installed qulacs as explained in the README.md via

```bash
cd System
git clone https://github.com/qulacs/qulacs.git
cd qulacs
./script/build_gcc.sh
cd build
make shared
```

and created (in another directory) the file `observables.cpp` with the same Code as in the Documentation:

```cpp
#include <cppsim/observable.hpp>
#include <string>

int main() {
    unsigned int n = 5;
    double coef = 2.0;
    std::string Pauli_string = "X 0 X 1 Y 2 Z 4";
    Observable observable(n);
    observable.add_operator(coef,Pauli_string.c_str());
    return 0;
}
```

When I try to compile now via 
```bash
g++ -O2 -I ~/System/qulacs/include -L ~/System/qulacs/lib observables.cpp -lvqcsim_static -lcppsim_static -lcsim_static -fopenmp -o observables
```
I get the following error:
```
/usr/bin/ld: /home/janlukas/System/qulacs/lib/libcppsim_static.a(pauli_operator.cpp.o): in function `PauliOperator::get_transition_amplitude(QuantumStateBase const*, QuantumStateBase const*) const':
pauli_operator.cpp:(.text+0x52f): undefined reference to `transition_amplitude_multi_qubit_Pauli_operator_partial_list_host(unsigned int const*, unsigned int const*, unsigned int, void*, void*, unsigned long long, void*, unsigned int)'
/usr/bin/ld: /home/janlukas/System/qulacs/lib/libcppsim_static.a(pauli_operator.cpp.o): in function `PauliOperator::get_expectation_value(QuantumStateBase const*) const':
pauli_operator.cpp:(.text+0x1456): undefined reference to `expectation_value_multi_qubit_Pauli_operator_partial_list_host(unsigned int const*, unsigned int const*, unsigned int, void*, unsigned long long, void*, unsigned int)'
collect2: Fehler: ld gab 1 als Ende-Status zurück
```

Checking the contents of `qulacs/lib/libcppsim_static.a` there is indeed no `transition_amplitude_multi_qubit_Pauli_operator_partial_list_host` to find:
```bash
cd qulacs/lib
ar -t libcppsim_static.a
circuit.cpp.o
circuit_optimizer.cpp.o
gate.cpp.o
gate_factory.cpp.o
gate_matrix.cpp.o
gate_matrix_diagonal.cpp.o
gate_matrix_sparse.cpp.o
gate_merge.cpp.o
general_quantum_operator.cpp.o
noisesimulator.cpp.o
observable.cpp.o
pauli_operator.cpp.o
qubit_info.cpp.o
simulator.cpp.o
state.cpp.o
state_gpu.cpp.o
utility.cpp.o
```

My g++ version is 10.2.0.

Is anyone having the same issue or can tell me, what I am doing wrong?

**Comment by corryvrequan** [comment]
Hi @jlbosse . Thanks for report.
`transition_amplitude_multi_qubit_Pauli_operator_partial_list_host` is a function to execute GPU kernels, and removed when binary is built without GPU. So, it is strange that the binary refers to the GPU functions though it is built without GPU.
Note that the prototype definition of this function can be found here:
https://github.com/qulacs/qulacs/blob/master/src/gpusim/stat_ops.h

Since Qulacs is not tested for gcc<=9, I first thought this is because our CMake script is not compatible with gcc-10.
I tested your codes `observable.cpp` in my environment with gcc-10, but it properly works. So, this is not because of the use of the latest gcc.

I suspect this happens because the build script is not properly configured. 
Can I ask you to check the following?

1. Confirm qulacs is build with `./script/build_gcc.sh`, not `./script/build_gcc_with_gpu.sh`.
2. Please confirm that there is no `libgpusim_static.a` in `~/System/lib/` folder.
3. You will see the following message just after executing `./script/build_gcc.sh`
```
-- The C compiler identification is GNU 10.1.0
-- The CXX compiler identification is GNU 10.1.0
-- Check for working C compiler: /usr/bin/gcc-10
-- Check for working C compiler: /usr/bin/gcc-10 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++-10
-- Check for working CXX compiler: /usr/bin/g++-10 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- USE_SIMD = Yes
-- USE_OMP = Yes
-- USE_GPU = No
-- USE_TEST = Yes
-- USE_PYTHON = Yes
```
Here, "USE_GPU" is assigned to NO?

If any of the above checks is not satisfied, Qulacs seems to be build depending on GPU library, and need libgpusim_static.a.

**Comment by jlbosse** [comment]
Thank you for the quick answer.

Indeed, I seem to have mangled up my installation with `./script/build_gcc_with_gpu.sh`. Deleting the whole repo, cloning and compiling everything again fixed it.

But out of curiousity: What would I need to change in the source code and the compile command to run my (C++) circuits on the GPU?

**Comment by corryvrequan** [comment]
I'm glad it was resolved.

> What would I need to change in the source code and the compile command to run my (C++) circuits on the GPU?

Yes.
To use GPU for simulation, qulacs binaries must be built with `./script/build_gcc_with_gpu.sh`. 
Then, you can use the class `QuantumStateGpu` defined in `cppsim/state_gpu.hpp` instead of `QuantumState` to allocate quantum state vector on GPU. Every function to modify the state vector allocated on GPU is processed with GPU.
Finally, the source code must be compiled including `-lgpusim_static`.

**Comment by jlbosse** [comment]
Thank you for your help.

For others having the same issue: On my machine I had to additionally tell the linker where to find the CUDA shared libraries. On 64-bit Arch Linux that was `/opt/cuda/lib64`
and hence the complete compile command is

```bash
g++ -O2 -I ~/System/qulacs/include -L ~/System/qulacs/lib -L /opt/cuda/lib64 <myfile>.cc -Wl,--start-group -lcppsim_static -lvqcsim_static  -lcsim_static -lgpusim_static -fopenmp -lgpusim_static -lcudart -lcublas -Wl,--end-group -o <myfile>
``` 

where the `-Wl,--start-group` and `-Wl,--end-group` are neccessary because I didn't figure the exact order of dependencies out.
