### ISSUE TITLE
No speedup when using qulacs-gpu

### ISSUE THREAD

**Issue by JoeGibbs88** [qulacs/qulacs#281]
I have been using the Python version of qulacs for simulations of variational quantum algorithms, and I wanted to try out qulacs-qpu to speedup my optimisations. After swapping out all instances of QuantumState for QuantumStateGpu, I was disappointed to find my code actually ran slower (running on Tesla V100). Please can you advise me if there are any other modifications to my script I need to make before I see a speedup with the gpu version.

**Comment by corryvrequan** [comment]
Hi @JoeGibbs88 
Thanks for considering using qulacs for your project. 
While details depend on the specific codes, there are several directions to utilize GPU.

1. Increase the size of quantum circuits
The performance graphs are shown in README page of qulacs. As you can see, when the number of qubits is smaller than about 20, GPU simulator is basically slower than CPU. This is because GPU function call requires constant-time overheads (about 1ms), which are not negligible compared with the computing time itself. Thus, to gain a speed-up with GPU, simulation time must be longer than the overhead. This means we need large circuits to observe speed-up by GPU.

2. Minimize communication between GPU and RAM
If you use functions such as "state.get_vector()" or "state.load(<numpy_vector>)", for example, to initialize quantum state or calculate observables in each iteration of VQE, this should be avoided in the case of GPU simulator if possible. Functions that return large objects such as state vector transfer large data between GPU and Main RAM. This causes additional overhead.
If you use it, I recommend benchmarking time for circuit simulation (`circuit.update_quantum_circuit()`) and the whole computing time. If whole computing time is much longer than circuit simulation time, there would be another bottle-neck and should be achieved with a faster way.
For the above example cases, observable evaluation can be achieved with `Observable`, and initialization of vectors with `state.set_computational_basis`.

**Comment by JoeGibbs88** [comment]
Thanks for the informative answer!
