### ISSUE TITLE
Equivalent of apply_qubit_operator()

### ISSUE THREAD

**Issue by auroraustc** [qulacs/qulacs#284]
Hello!
Is there a method to act a Hamiltonian on a state instead of calculating the expectation value of the Hamiltonian?
The get_expectation_value() function calculates ![](http://latex.codecogs.com/gif.latex?\\langle\\psi_{old}|\\hat{H}|\\psi_{old}\\rangle). However, sometimes the ![](http://latex.codecogs.com/gif.latex?|\\psi_{new}\\rangle=\\hat{H}|\\psi_{old}\\rangle) is needed for further use. ![](http://latex.codecogs.com/gif.latex?\\hat{H}) can be the summation of some Pauli strings.
In ProjectQ, I can do this by calling the `eng.backend.apply_qubit_operator()`. Is there any equivalent functions in qulacs?
Thank you!

**Comment by auroraustc** [comment]
Here is my simple try which can get the final state vector of  ![](http://latex.codecogs.com/gif.latex?|\\psi_{new}\\rangle=\\hat{H}|\\psi_{old}\\rangle):

```python
def final_state(qubitOp: openfermion.QubitOperator,
                state,
                n_qubits: int):
    gate_matrix_dict = {
        "X": qulacs.gate.X,
        "Y": qulacs.gate.Y,
        "Z": qulacs.gate.Z
    }
    gate_list = []
    coeffs = []
    qubitOp_list = list(qubitOp)
    for i in range(len(qubitOp_list)):
        qubitOp_i = qubitOp_list[i]
        terms_i = list(qubitOp_i.terms.keys())[0]
        coeff_i = qubitOp_i.terms[terms_i]
        coeffs.append(coeff_i)
        gate_list_i = []
        for idx_i, gate_i in terms_i:
            gate_list_i.append((gate_i, idx_i))
        gate_list.append(gate_list_i)
    H_state_vec = numpy.zeros(2 ** n_qubits, dtype=numpy.complex)
    for i in range(len(coeffs)):
        temp_state = state.copy()
        gate_list_i = gate_list[i]
        coeff_i = coeffs[i]
        if len(gate_list_i) != 0:
            merged_gate_i = qulacs.gate.merge(
                [gate_matrix_dict[gate_apply](idx_apply) for gate_apply, idx_apply in gate_list_i])
            merged_gate_i.update_quantum_state(temp_state)
        H_state_vec += temp_state.get_vector() * coeff_i
    return H_state_vec.reshape([-1, 1])
```

However, this implementation runs very slow and will cause the following error if use GPU:
```bash
Error: /tmp/pip-install-i4m71457/qulacs-gpu_80427ddb44af4fcea687ca838cb08cdd/src/gpusim/update_ops_multi.cu:840, code: 701, reason: too many resources requested for launch
```

**Comment by corryvrequan** [comment]
Thanks for considering using qulacs for your projects.
Your codes seem correctly implemented but I have several comments for efficient use of qulacs.

###  Avoid copying state vector in each loop

You are using
`temp_state = state.copy()`
in each allocation.
This allocates and deallocates O(2^n) state vector in each loop, which would be time-consuming.

Once state vector is allocated with copy operation at first,
`temp_state = state.copy()`
then, you can reuse the allocated space by load function
`temp_state.load(state)`

###  Avoid merge Pauli gate

`qulacs.gate.merge` will merge two gates into a single gate as dense matrix gates.
On the other hand, qulacs has optimized gates for the product of Pauli matrices.
Since the Pauli matrix is sparse, the latter is much faster than before.

### Minimize the number of calls of `get_vector`

State vector class has a function `add_state` to create superposition and `multiply_coef` to multiply coefficients.
With these functions, the state vector is updated without copying the data of the state vector from qulacs to the NumPy array.

### About GPU error

In the execution of Qulacs GPU, qulacs tries to put gate matrix data on GPU's fast and small memory space.
However, in several GPU models, we are reported that this memory space is not sufficient when too large a dense matrix gate is applied. I think this problem is resolved by avoiding using qulacs.gate.merge.

### Example code
As a summary, the following codes would be work.

```python
def final_state(qubitOp: openfermion.QubitOperator,
                state,
                n_qubits: int):
    gate_list = []
    coeffs = []
    qubitOp_list = list(qubitOp)
    for i in range(len(qubitOp_list)):
        qubitOp_i = qubitOp_list[i]
        terms_i = list(qubitOp_i.terms.keys())[0]
        coeff_i = qubitOp_i.terms[terms_i]
        coeffs.append(coeff_i)
        gate_list_i = []
        for idx_i, gate_i in terms_i:
            gate_list_i.append((gate_i, idx_i))
        gate_list.append(gate_list_i)

    H_state = None
    temp_state = None
    pauli_id_dict = {
        "X": 1,
        "Y": 2,
        "Z": 3
    }
    for i in range(len(coeffs)):
        if temp_state is None:
            temp_state = state.copy()
        else:
            temp_state.load(state)
        gate_list_i = gate_list[i]
        coeff_i = coeffs[i]
        if len(gate_list_i) != 0:
            target_list = [idx for _, idx in gate_list_i]
            pauli_list = [pauli_id_dict[pauli] for pauli, _ in gate_list_i]
            merged_gate = qulacs.gate.Pauli(target_list, pauli_list)
            merged_gate.update_quantum_state(temp_state)
        temp_state.multiply_coef(coeff_i)
        if H_state is None:
            H_state = temp_state.copy()
        else:
            H_state.add_state(temp_state)
    return H_state
```

**Comment by auroraustc** [comment]
Hello!
Thank you for your reply! The problem is successfully resolved, thank you so much!
