### ISSUE TITLE
RX(x) is  exactly RX(-x)?

### ISSUE THREAD

**Issue by yuguoshao** [qulacs/qulacs#291]
![image](https://user-images.githubusercontent.com/61077538/132443737-9724fcde-4ce5-4117-8953-5670bac68196.png)
In qulacs , Rx(x) is Rx(-x) in wiki?
![image](https://user-images.githubusercontent.com/61077538/132443987-be01f66c-f6db-4ad8-a9c7-23807254777d.png)

**Comment by TysonRayJones** [comment]
Hi there,

I'm not a qulacs dev, but am just weighing in since I happened to see this issue.

Indeed, as per [the manual](http://docs.qulacs.org/en/latest/guide/2.0_python_advanced.html#Quantum-gates), qulacs adopts the convention:
> Rx(theta) = exp(i X theta/2)

The choice of prefactor of `X i theta` (in qulac's case, `1/2`, and in Wikipedia's, `-1/2`) is really arbitray, and Wikipedia certainly isn't the authority. In some applications, where you apply `Rx` with its exponentiated form in mind, it can be _more_ confusing to use the negative pre-factor. 

Anything of the form
```
exp( X i theta alpha)
```
where `alpha` is a real parameter, is an effective rotation around the x-axis, i.e. `Rx`. I have personally seen, between simulators and notation in papers, all of:
```
Rx = exp(     i X theta)
Rx = exp(     i X theta / 2 pi )
Rx = exp( 1/2 i X theta)
Rx = exp(-1/2 i X theta)
```

It does seem a prefactor `-1/2` is an emerging convention in simulators, though I presonally prefer `1`. In any case, it's just another reminder to always [read the manual](https://en.wikipedia.org/wiki/RTFM)! :)
