### ISSUE TITLE
Circuit debug info doesn't print

### ISSUE THREAD

**Issue by AFOEK** [qulacs/qulacs#301]
I try to print circuit info using `iostream`, using Linux WSL but it not print out any result.
here is my code:
```
#include <iostream>
#include <cppsim/state.hpp>
#include <cppsim/circuit.hpp>
#include <cppsim/observable.hpp>
#include <cppsim/gate_factory.hpp>
#include <cppsim/gate_merge.hpp>
using namespace std;
int main(){
    unsigned int n = 2;
    QuantumState state(n);
    state.set_zero_state();

    QuantumCircuit circ(n);

    circ.add_CNOT_gate(0,1);
    circ.add_H_gate(0);
    circ.update_quantum_state(&state);
    std::cout << circ << std::endl;
    return 0;
}
```
It's just print out how many qubit, step and etc. I expect result ?

**Comment by corryvrequan** [comment]
Hi @AFOEK .
I successfully got the following strings when I tested your codes in my WLS environment with g++-9.3.0.
```
*** Quantum Circuit Info ***
# of qubit: 2
# of step : 2
# of gate : 2
# of 1 qubit gate: 1
# of 2 qubit gate: 1
Clifford  : yes
Gaussian  : no
```
Thus, I think there is no problem with your source codes. 

A possible reason why nothing is printed is that your program crashes before printing strings. You can check whether your program crashes or not by inserting `std::cout << "test" << std::endl;` just before `return 0;`. If nothing is printed, I guess "update_quantum_state" crashes due to an inconsistent compilation setting.
(While a certain message should be printed when a program crashes, programs in WSL sometimes does not output "segmentation fault (core dumped)" even if it crashes by a segmentation fault.)

If so, please check the following two points.
1. Please verify that you follow the compile process written in https://github.com/qulacs/qulacs#build-with-gcc
Note that `-O2` and `-fopenmp` are necessary to be consistent with static libraries, while I guess compilation fails without these options.

2. Please try disabling SIMD optimization.
Qulacs uses SIMD instructions to speed up the simulation. While this option is automatically disabled when the CPU does not support them, the program will crash if the detection of supports does not work. You can force disabling them by replacing L31 of `./script/build_gcc.sh` to
```
cmake -G "Unix Makefiles" -D CMAKE_C_COMPILER=$GCC_COMMAND -D CMAKE_CXX_COMPILER=$GXX_COMMAND -D CMAKE_BUILD_TYPE=Release -D USE_SIMD:STR=No ..
```
and build them again.

Please let me know if the above does not work. The information of your compiler with its version and the name of your CPU would be informative for further comments.

**Comment by AFOEK** [comment]
my ```lscpu``` output:
```Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               126
Model name:          Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
Stepping:            5
CPU MHz:             1190.403
BogoMIPS:            2380.80
Virtualization:      VT-x
Hypervisor vendor:   Microsoft
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            512K
L3 cache:            6144K
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx512vbmi umip avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm flush_l1d arch_capabilities```
fyi I use WSL for trying before I install to my real hardware

**Comment by corryvrequan** [comment]
Sorry for late reply.
As far as I googled, your CPU supports AVX2, thus it is mysterious to me that your program does not output anything.
If you have installed CMake, git, and gcc, I believe you can build qulacs from source with the following command.
```
pip install qulacs --no-binary :all:
```
I think qulacs installed with the above command does not invoke any issue.

**Comment by AFOEK** [comment]
I recently try run it again... It output same as yours... it seems it works... If I want to get the each qubit probability how I get it ? (I just make bell state for this testing)

**Comment by KowerKoint** [comment]
Sorry for very late reply.
You can get the probability of each qubit by using `StateVector::get_zero_probability`, or you can get the raw data of state vector by constructing `std::vector<CPPCTYPE>(state_vector.data_cpp(), state_vector.data_cpp() + state_vector.dim())`
