### ISSUE TITLE
[Question] DenseMatrix Gates Taking Too Long via Python - Custom Gates at C++ Backend Level?

### ISSUE THREAD

**Issue by onurdanaci** [qulacs/qulacs#573]
Hi,

I tried to inject 256 x 256 (8 qubit) dense matrices into state vector simulation via Qulacs Python interface, but it is taking too long to process & simulate. Even more than just multiplying these matrices with the initial state vector in Numpy!

I suspect this is an artifact of communication overhead between Python -> pybind11 -> C++ backend, and coming back. Because equivalent simulations (using native gates of Qulacs that have almost the same matrices as the one I feed by DenseMatrix wrapper) take much less time.

I was wondering if there is a way to mitigate that. Or, alternatively, is there a way I create those custom dense matrix gates at C++ level, by somehow serializing these gates as CSV files or something, and accessing them via Python as Qulacs' new native gates (to make it run as fast as the Qulacs' simulations with native gates)?

Thank you for your time.
Best,
Onur

**Comment by forest1040** [comment]
Thank you for question!

Named gates are fast because they are optimized for their processing.
DenseMatrix is slower than named gates because it does matrix calculations, but it shouldn't be that slow.
How many DenseMatrix units do you use?
Also, qulacs now uses OpenMP threads with the number of cores your PC has.
If the quantum circuit size is around 8, you may want to set it below because you don't need many threads.
```
export OMP_NUM_THREADS=1
```
On the other hand, if you have a large circuit size, you may want to use more threads. Or GPU.
