### ISSUE TITLE
Could you please also benchmark Yao.jl?

### ISSUE THREAD

**Issue by GiggleLiu** [qulacs/qulacs#99]
Here is a Julia package, also for variational quantum circuits (Quantum Software 2.0), Yao.jl
https://github.com/QuantumBFS/Yao.jl

It has better performance than projectQ
https://quantumbfs.github.io/Yao.jl/stable/dev/benchmark/

It also has GPU support
https://github.com/QuantumBFS/CuYao.jl/issues/1

It is definitely interesting to see which one is faster. If you agree, I can submit a PR about the benchmark code. Also, any technical problem about using Julia is welcome in this issue~

**Comment by corryvrequan** [comment]
Thank you for nice suggestion, @GiggleLiu, and sorry for very late reply.

We plan to totally update benchmarking environment and methods in this month, and we plan to add simulators, including Yao.jl.
Since we will let all the benchmarking codes public, we are happy if you could give us comments on our benchmarking codes after that.

**Comment by Roger-luo** [comment]
Let us know if there's any issue on using the benchmarking. I'd suggest we could set up a repo for benchmarking like this famous convnet benchmark: 

https://github.com/soumith/convnet-benchmarks

So people could update new benchmarks etc. based on your existing code (if other software author think that is not the best practice, which would be more fair)

**Comment by Roger-luo** [comment]
I recently make yet another benchmark here: https://github.com/Roger-luo/quantum-benchmarks
